### ISSUE TITLE
D7 migration path: enable dependency entity_plus in update hook

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/rules#138]
Sorry, super short issue description...

From our Zulip chat:

> Fatal error: Class 'EntityPlusControllerExportable' not found in .../modules/rules/includes/rules.core.inc on line 55
> 
> entityplus is available as module in backdrop (and does contain this class). Was not enabled in D7, because I never had it there.
> 
> so my guess is, backdrop can not find it, because it is not enabled. But how would I enable that before upgrade if it is not there in D7?

Proposed solution: `module_enable()` in an update hook. Or get rid of the dependency. Whatever works.

**Comment by bugfolder** [comment]
Same goes for Entity UI module (like Entity Plus, also required for Rules, and also not a module in Drupal).

As a stop-gap, we can/should create a page for the Wiki with Drupal stub modules like [Upgrading Ubercart from Drupal 7 · backdrop-contrib/ubercart Wiki](https://github.com/backdrop-contrib/ubercart/wiki/Upgrading-Ubercart-from-Drupal-7).

**Comment by laryn** [comment]
See also: https://github.com/backdrop-contrib/entity_plus/issues/47

**Comment by bugfolder** [comment]
Wiki page added https://github.com/backdrop-contrib/rules/wiki/Upgrading-Rules-from-Drupal-7. README file still needs to mention it.

**Comment by bugfolder** [comment]
The mention of stub modules is now in the README file.

**Comment by bugfolder** [comment]
Better yet: per a suggestion and example from @Laryn (https://github.com/backdrop-contrib/manualcrop/commit/033d6c4cf80186292fbf6089e1f6b84c15ce4fbd), we can do this during hook_requirements().

**Comment by bugfolder** [comment]
But this PR isn't fully ready yet.

**Comment by bugfolder** [comment]
And now it is ready. Because the current dev version of Rules has dependencies on dev versions of other modules (e.g., Entity Plus), here's how I tested the upgrade:

* Create a D7 site with D7 Rules module enabled.
* Create a B codebase pointing to the D7 db, with the current recommended versions of Rules (1.x-2.2.0), Entity Plus (1.x-1.0.14), Entity UI (1.x-1.0.0-beta), and Entity Tokens (1.x-2.0.0-rc1).
* Create a Git patch for this PR and apply it to the B version of Rules.
* Run update.php on the B site.

It runs, and as far as I can tell, everything is working properly!

Note that there's a sorta hack in `rules.module` that's needed to avoid a crashing bug during the update process.

**Comment by argiepiano** [comment]
Great! I'll test. 

I think this should become a model for other contrib modules that depend on Entity Plus. Here's a short list:

- Ubercart
- Entity Tokens
- Registration
- References dialog
- Video Embed field
- Field collection
- Paragraphs
- OG
- Replicate
- Inline entity form
- Search API
- Membership entity
- GDPR cookie

Perhaps we should ping those maintainers?

**Comment by bugfolder** [comment]
> Perhaps we should ping those maintainers?

We should check to verify that if multiple modules use the same implementation in their `hook_requirements()` that there's not some unexpected interaction. For example, if Ubercart and Rules both try to enable the B-only modules they need in the requirements phase, there's nothing bad that happens from out-of-order enablement.

I also am starting to wonder if there should be a core API specifically for this situation during upgrades, where a B module has B-only module dependencies that should be enabled prior to `hook_update_N()` calls. And/or whether instead of using full-blown `module_enable()`, which calls a whole bunch of hooks (hence requiring the Rules hack), if there should be a sort of `module_enable_lite()` that enables them without invoking some of the hooks.

I don't know the answer to these, but I'd suggest we do some further testing. Although we could perhaps enlist some of the maintainers of those modules to help with testing.

**Comment by argiepiano** [comment]
I've tested this and it works well. I added a `hook_requirements()` to Entity Tokens to test if there was any conflict when two modules (Rules and Entity Tokens) needed to enable Entity Plus.  No problems there.

> I also am starting to wonder if there should be a core API specifically for this situation during upgrades, where a B module has B-only module dependencies that should be enabled prior to hook_update_N() calls. And/or whether instead of using full-blown module_enable(), which calls a whole bunch of hooks (hence requiring the Rules hack), if there should be a sort of module_enable_lite() that enables them without invoking some of the hooks.

This would make a lot of sense.

**Comment by argiepiano** [comment]
@bugfolder, I've played around a bit with your PR. I'm going to add some comments to it

1. The stuff inside the `if (empty($module_files)) {}` is not necessary. The update script actually checks to see if the required modules (entity_plus and entity_ui) are present in the modules folder, and if not, it stops the upgrade process.
2. The `else{}` in that statement is necessary, since in fact it enables the required modules (which the update script doesn't do). So this else statement can be rewritten to `if (!empty($module_files)) {}`

I also noticed that the first hook_permissions firing performed by the script happens as part of the invocation of `update_check_requirements($skip_warnings)` in line 535 of the script - that is, before any of the update hooks are run. Which is a good thing.

So, I'm wondering if perhaps we can modify  core's `update_check_requirements()` (or the functions it invokes) to actually enable the dependencies that are present in the folder. This would be a more efficient approach than using hook_requirements.

**Comment by bugfolder** [comment]
> 1. The stuff...is not necessary.

Yeah, I realized shortly thereafter that if the module is properly included in the .info file, this branch of the code is not needed.

> So, I'm wondering if perhaps we can modify core's update_check_requirements() (or the functions it invokes) to actually enable the dependencies that are present in the folder. This would be a more efficient approach than using hook_requirements.

Agreed, and I'll start a core issue on that. I want to think about what to suggest though. I don't know if simply "always enable a module if it's called for in dependencies and exists in the code base" would pass muster. (Maybe it would.) So the issue will need some writeup and discussion to start with.

**Comment by argiepiano** [comment]
>  So the issue will need some writeup and discussion to start with.

Agreed. I was going to try some options tonight and discuss some solutions with you, so that those can be presented in the core issue. I'll try to get to it. If you get to it first I'd love to hear what you come up with.

**Comment by bugfolder** [comment]
This issue is on hold while the core issue https://github.com/backdrop/backdrop-issues/issues/5499, which would provide a core fix, is being discussed and developed.

**Comment by bugfolder** [comment]
Closing this issue because https://github.com/backdrop/backdrop-issues/issues/5499 is now fixed in core and handles the problem.
