### ISSUE TITLE
Rules is inconsistent about the machine name of reaction rules

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#217]
To see this in action, create a Rule with the name "Test Rule," which will claim to have a machine name of `test_rule`, as here:

<img width="859" alt="image" src="https://github.com/backdrop-contrib/rules/assets/29214084/746042a7-348b-438c-8a9b-a8342942bc1b">

But once it is saved, it will have the machine name `rules_test_rule`:

<img width="996" alt="image" src="https://github.com/backdrop-contrib/rules/assets/29214084/858d6f2a-9a14-4f1e-88be-cf9994a9bfbe">

Presumably, we want to stick to the actual behavior of prepending `rules_` to what is entered on the Rules creation page, since who knows what might break within Rules if we changed it (?). But then we should alter the displayed message to accurately reflect what is going to happen.

**Comment by argiepiano** [comment]
Good catch. I think we can solve this the same way the Manage Fields UI handles it. It uses the property `#field_prefix` when you first enter the name of the field, so that the machine name appears to have the prefix `field_` (in this case it will be `rules_`. This prefix is not added to the submitted form element - it's only a visual thing.

See [this line](https://github.com/backdrop/backdrop/blob/266a5018c5e675ee88e51dd6e732da3ec464a696/core/modules/field_ui/field_ui.admin.inc#L483).

**Comment by bugfolder** [comment]
Thanks for the tip on how to solve, @argiepiano! PR submitted. Here's how it looks:

![image](https://github.com/backdrop-contrib/rules/assets/29214084/12facba3-787c-4b1f-b64e-cd3ae0022475)

And if we edit the machine name:

![image](https://github.com/backdrop-contrib/rules/assets/29214084/129a08a8-6947-44b9-ab67-9fc96e17a2b3)

**Comment by argiepiano** [comment]
LGTM!
