### ISSUE TITLE
Sending mail to users of a role

### ISSUE THREAD

**Issue by barneylodge** [backdrop-contrib/rules#26]
When tasing this action on two separate installations I get

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r.rid' in 'where clause': SELECT DISTINCT u.mail FROM {users} u INNER JOIN {users_roles} r ON u.uid = r.uid WHERE r.rid IN (owner); Array ( ) in rules_action_mail_to_users_of_role() (line 111 of /var/www/html/modules/rules/modules/system.eval.inc).

**Comment by Graham-72** [comment]
@barneylodge it looks as though the code at line 111 of system.eval.inc should be ... `WHERE r.role IN`... rather than ....`WHERE r.rid IN` ....
Are you able to try this edit yourself? I will try it as soon as I can, maybe within 24 hours.

**Comment by barneylodge** [comment]
Wow...thanks. I will take a look

**Comment by barneylodge** [comment]
Have updated file and we're getting closer. The role is identified but I now have this error

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'owner' in 'where clause': SELECT DISTINCT u.mail FROM {users} u INNER JOIN {users_roles} r ON u.uid = r.uid WHERE r.role IN (owner); Array ( ) in rules_action_mail_to_users_of_role() (line 111 of /var/www/html/modules/rules/modules/system.eval.inc).

It also reports "invalid address" on the error page

**Comment by Graham-72** [comment]
But this only fixes part of the issue.

**Comment by Graham-72** [comment]
@barneylodge in line 111 please try using double quotation marks around the db_query instead of the single ones. This seems to solve the problem in my testing but there may be some other problem.

So line 111 should be
 `$result = db_query("SELECT DISTINCT u.mail FROM {users} u INNER JOIN {users_roles} r ON u.uid = r.uid WHERE r.role IN ('. $rids .')");`

Also, line 105 should use `BACKDROP_AUTHENTICATED_ROLE` not `BACKDROP_AUTHENTICATED_RID`.

If these changes work for you I will update the github repository and create a new release. However, there are no doubt other instances where the port to BD is not fully complete.

**Comment by barneylodge** [comment]
Wow this is such good service!! Very grateful..I will test

Regards

Barney Lodge
(Sent from my iPhone)

**Comment by barneylodge** [comment]
Hi Graham

The changes have stopped the errors, although for some reason mail is not
being sent.

However I switched to using the "send HTML mail to users of a role" rule,
and after modifying mimemail.rules.inc, with your changes, all works well.

So I have something I can use and I am very grateful.


Barney Lodge

**Comment by Graham-72** [comment]
Hi Barney
You are very welcome. I will soon try and see why the mail is not being sent,

**Comment by herbdool** [comment]
@Graham-72 I've got a fix here https://github.com/backdrop-contrib/rules/pull/54 - I've tested and it works.

**Comment by Graham-72** [comment]
@herbdool thanks. I have included it in a new release of Rules.

**Comment by Graham-72** [comment]
I'm closing this issue because I think it is all dealt with now.
