### ISSUE TITLE
Problems with installation of Rules module

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/rules#37]
@amilenkov reported here https://github.com/backdrop/backdrop-issues/issues/3604 and copying it to the appropriate project:

----
**Description of the bug**
I tried several times to install Rules module. With the necessary "entity" modules dependencies. About two weeks ago with Backdrop 1.12.2 and rules-1.x-2.0.2.
Today I tried again with Backdrop 1.12.5 and Rules 1.x-2.1.0.

I did it both through admin/modules/install as well as through FTP - manually upload and activate.

In all attempts I receive the same error: White screen with message: 

Fatal error: Declaration of RulesRuleUI::form(&$form, &$form_state, $options = Array) must be 

compatible with RulesActionContainerUI::form(&$form, &$form_state, $options = Array, $iterator 

= NULL) in /home/remoogme/public_html/modules/rules/ui/ui.plugins.inc on line 80

After which the site is unavailable, you cannot log in as a user and the only one that fixes this is deleting the database and importing the db backup through phpMyAdmin.

**Comment by herbdool** [comment]
@amilenkov unfortunately, the change in dependencies mixed with complex modules makes this hard to pinpoint. Might be something to do with upgrading rather than a fresh install. I just tried a fresh install with the latest versions and didn't get your error. If you're able I suggest trying to uninstall completely and reinstall, though that might have its own issues. Good luck

**Comment by amilenkov** [comment]
I Keep trying to install Rules. 

I Work on shared hosting with PHP 7.2. I deleted the entire site and the database and I made a brand new installation with Backdrop 1.12.5 and latest rules-1. x-2.0.2. Without any other modules and content installed. I Get the same error and the site becomes unavailable - white screen with the above sited error message. 

After that I do the same again, a new installation of Backdrop 1.12.5. Now, however, I install the Rules dependency modules one by one:
- Entity Plus 1.x-1.0.3 - installed OK
- Entity_ui- v 1.x-1.0.0-beta - installed OK
- rules-1.x-2.0.2 - ERROR - the same white screen and same error message.

Start again with deleting all files from the server and all tables from database. But this time i installed:
- backdrop-1.11.3
- rules-1.x-2.x (saved from 2016 year) - this versions of rules has no entity dependency modules.

This time everything works fine and I have working Rules.
I Know I could have tried upgrading the system and Rules. But I will not do it because even if it becomes successful, I will know that there is a risk and the latest versions of Backdrop and Rules have some problem.

Even more I do not know how I would do this with the site for which I need this configuration - it is already built with Backdrop 1.12.5., there are dozens of other modules instated and I do not want to risk it. At least I realized that the additional modules are not the cause of the error - it also appears with a brand new installation without any additional modules. 

I'm not in a hurry, I'll wait for another version of Rules. But I guess this is an unpleasant problem for people who rely on Rules as their main functionality in their website.

**Comment by amilenkov** [comment]
Additional info to someone who might be interested:

I needed a Rules module to receive messages when someone published a new content or comment on the site. Rules is a great module and will look forward to it to work without problems.

But so far I found a temporary solution and it works well – with Trigger Actions:

https://backdropcms.org/project/trigger_actions

**Comment by herbdool** [comment]
> After that I do the same again, a new installation of Backdrop 1.12.5. Now, however, I install the Rules dependency modules one by one:
> 
> Entity Plus 1.x-1.0.3 - installed OK
> Entity_ui- v 1.x-1.0.0-beta - installed OK
> rules-1.x-2.0.2 - ERROR - the same white screen and same error message.

@amilenkov have you tested with a brand new installation using the latest Rules release? https://github.com/backdrop-contrib/rules/releases. You mention a fresh install but you used an older version. I tried with Rules 1.x-2.1.0, Entity Plus 1.x-1.0.3, Entity UI 1.x-1.0.0-beta on a fresh install and didn't get an error. It's using PHP 7.0 (It'll take me more work to test with 7.2 or 7.3 so I haven't yet).

Rules 1.x-2.1.0 change dependencies from entity_metadata_wrapper to entity_plus so you definitely can't use older versions of Rules with Entity Plus.

**Comment by amilenkov** [comment]
Thanks @herbdool !!!

I repeated it all with a brand new installation on test site of:
Rules 1.x-2.1.0
Entity Plus 1.x-1.0.3
Entity UI 1.x-1.0.0-beta
Using PHP 7.0

Everything was installed correctly and I managed to create several rules that were working normal.

Tomorrow I will do the same with the real productive site and I will report the results.

I am now happy and become proud to work with Backdrop CMS !!!

**Comment by amilenkov** [comment]
As I wrote on March 24, on a brand new installation of Backdrop 1.12.5 I successfully installed:

Rules 1. x-2.1.0
Entity Plus 1. x-1.0.3
Entity UI 1. x-1.0.0-beta
Using PHP 7.0

Today I tried the same on another site, which is not a new installation, but has been upgraded to 1.12.5 from previous versions of Backdrop and there are many other modules.

The Installation ended with multiple warnings:

    Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_crud_get_info() (line 127 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: in_array() expects parameter 2 to be array, boolean given in entity_plus_crud_get_info() (line 127 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_entity_info_alter() (line 199 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: in_array() expects parameter 2 to be array, boolean given in entity_plus_entity_info_alter() (line 199 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_entity_info_alter() (line 199 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: in_array() expects parameter 2 to be array, boolean given in entity_plus_entity_info_alter() (line 199 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_crud_get_info() (line 127 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: in_array() expects parameter 2 to be array, boolean given in entity_plus_crud_get_info() (line 127 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_entity_info_alter() (line 199 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: in_array() expects parameter 2 to be array, boolean given in entity_plus_entity_info_alter() (line 199 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_crud_get_info() (line 127 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: in_array() expects parameter 2 to be array, boolean given in entity_plus_crud_get_info() (line 127 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_type_supports() (line 180 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: in_array() expects parameter 2 to be array, boolean given in entity_plus_type_supports() (line 180 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
--------------------------

After installation of Rules I created a simple test rule - send an e-mail after post of comment. This rule works as expected and I relieved the message from the system .

But in the page admin/config/workflow/rules there is a warning: 

    Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_crud_get_info() (line 127 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).
    Warning: in_array() expects parameter 2 to be array, boolean given in entity_plus_crud_get_info() (line 127 of /home/remoogme/public_html/modules/entity_plus/entity_plus.module).

I will uninstall Rules 1. x-2.1.0, Entity Plus 1. x-1.0.3, Entity UI 1. x-1.0.0-beta and restore back to a previous version of the site from a backup.

I'll try again when later versions appear, so far I don't seem to be sure to work with these modules.

I also have to note that the installation was made, albeit with warnings, with PHP 7.0 (and test simple rule was working), with PHP 7.3  the installation was impossible and a white screen with error appears and the site becomes unavailable for login.

Thanks for a very useful job on Rules for Backdrop. I believe that Rules will be an extremely important advantage of Backdrop in comparison to other CMS.

**Comment by herbdool** [comment]
@amilenkov can you search all the code on that site for the `BackdropDefaultEntityController` class? It's not clear where that is being defined.

**Comment by amilenkov** [comment]
Yes, I will do this tomorrow. Thanks!

**Comment by amilenkov** [comment]
Please note in addition:

I wrote "tomorrow" because I live and work in Bulgaria and here now it is late in the evening - 22:19.
Tomorrow I will do this search you have asked for. And send results.

But, don't you think, it would be more useful if I sent you all the data of the site - the public directory content, config directory and phpMyAdmin export of the database?

I can send a link for you to download these files. I think in such way you can duplicate the site and will have quite more information to analyze.

Sorry, I'm not an experienced developer – all I know about making sites is a result of self-education in the last 15-20 years.

I use even  Github with very limited capabilities. My strength is graphic design and content creation.

I suppose it will be useful for you (and probably for other members of the community of Backdrop)  to see in practice how an ordinary - non-professional user - as me - works with the system.

This is a site where I want to add Rules:
https://remonti-gebo.com
Small company for home repairs. 

The site is only in Bulgarian, but most administrative interface is in English.

**Comment by amilenkov** [comment]
@herbdool 
I find BackdropDefaultEntityController only in xmlsitemap_menu.module

'controller class' => 'BackdropDefaultEntityController',

line 26

**Comment by herbdool** [comment]
@amilenkov that looks like the cause of this particular fatal error. That should be `DefaultEntityController` not `BackdropDefaultEntityController`. I created an issue there https://github.com/backdrop-contrib/xmlsitemap/issues/82 - maintainer recently quit so I might help create a patch.

Thanks for your help on this. I'm not the maintainer of this module either so I'm just figuring this out as I go along and help create a patch or two. There are a lot of people in your shoes so I understand. Hopefully we can help get this working and @Graham-72 will make new releases with the fixes.

**Comment by amilenkov** [comment]
More Information, hope will be useful:

1. I deactivated and uninstalled XML Sitemap 1. x-1.0.4 module.

2. I did a successful installation of:
--- rules-1.x-2.1.0
--- entity_plus-1.x-1.0.3
--- entity_ui-1.x-1.0.0-beta

No Error Messages!!!

3. I installed instead Easy XML sitemap 1.x-1.0.12
It works fine and is really "easy".  Google says "success" for new sitemap.xml file.

4. I created 2 rules that sends messages to me when other user (not me) publish or edit content or comment. This is incomparably more convenient and powerful than using trigger_actions module.

All this works was done with PHP 7.0

After that I change hosting account (I use cPanel shared hosting with PHP Manager) to PHP 7.3.3

The page admin/config/workflow/rules become unavailable ! Only white screen, no message.

Change to PHP 7.2

The page admin/config/workflow/rules - unavailable again, white screen but with error message: 

Fatal error: Declaration of RulesRuleUI::form(&$form, &$form_state, $options = Array) must be compatible with RulesActionContainerUI::form(&$form, &$form_state, $options = Array, $iterator = NULL) in /home/remoogme/public_html/modules/rules/ui/ui.plugins.inc on line 0

Change to PHP 7.1.27

Rules admin pages are available without errors, two created rules work normally !!!
Status report is OK.

* * *
Thank you VERY MUCH for the help.

I will work with PHP 7.1.27 and Easy XML sitemap (when using Rules). I assured myself again how great and power system is Backdrop CMS - despite its childhood age. I Accept and understand all these difficulties, I have been working with Drupal since version 5 and I have witnessed how it gradually evolved and perfected.

Will be glad to see after some time a new version of XML Sitemap compatible with Rules. XML Sitemap has more options (than Easy XML sitemap)  for fine tuning of the sitemaps. But Easy XML sitemap is also perfect, especially for beginners.

I hope that this my report will help mastering of Rules and also help other users to work with Rules.

**Comment by herbdool** [comment]
Thanks for the testing @amilenkov. I think the issue for PHP 7.2 and up is related to this https://www.drupal.org/project/rules/issues/2923477. Hopefully that fix works here too.

**Comment by herbdool** [comment]
@amilenkov I've made a "pull request" which hopefully fixes (some?) of the issues in PHP 7.2+. If you feel up to testing you could try this patch https://patch-diff.githubusercontent.com/raw/backdrop-contrib/rules/pull/40.patch. That would help out quite a bit. You can either make the change manually in the code or search for online help on applying patches.
