### ISSUE TITLE
user_has_role(s) isn't evaluating correctly

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/rules#49]
I don't think it's working properly. My test rule works with it disabled but won't work with it there. I've tested a few different ways.

**Comment by herbdool** [comment]
@Graham-72 I've got a small fix for this https://github.com/backdrop-contrib/rules/pull/50. Can you please review and merge? Thank you.

**Comment by Graham-72** [comment]
@herbdool I am having difficulty testing this fix because I cannot get the Data Comparison evaluate function to work. It seems as though the Entity Plus module is not creating the EntityStructureWrapper and EntityBackdropWrapper objects that should reach the evaluate function in class Rule in `rules.plugins.inc`. Are you seeing this problem?

![Screenshot_2019-08-24 Content bdtest oliverhosting uk](https://user-images.githubusercontent.com/10559274/63633724-9e742b80-c644-11e9-861e-7cb4a5c67010.png)

**Comment by TheMetMan** [comment]
I have just tried **Issue backdrop-contrib#49 fix user_has_role(s)** and it works for me. 
Thanks for the fix.

**Comment by herbdool** [comment]
@TheMetMan thanks!

@Graham-72 it seems like you'd need to test this on a clean install. My change is pretty minor so it shouldn't affect Entity Plus, etc.

**Comment by herbdool** [comment]
I tested again and it still works for me. @Graham-72 don't try the Data Comparison, just choose User has Roles > then choose the role(s).

**Comment by Graham-72** [comment]
Yes it works. I must have been encountering some other problem. (Now tested with Backdrop 1.14.1).
