### ISSUE TITLE
"Show a message on the site" action should have the new "info" type

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rules#70]
![Screen Shot 2020-02-10 at 11 10 11 AM](https://user-images.githubusercontent.com/871421/74172486-f05e3d00-4bf5-11ea-9f8d-1885c33729ec.jpg)

**Comment by Graham-72** [comment]
@laryn thanks for suggesting this. Is my PR satisfactory?

**Comment by stpaultim** [comment]
@Graham-72 - I see that you just merged this. 

I tested it and I'm a bit confused, because I think that @laryn was suggesting that you add the info type which has been added to Backdrop core. Status, Error, Warning, and Info are each themed a differently. 

Your PR replaced the existing core type messages (4) with a different set of 9 types of messages. These new types don't have any core theming. When I tested them, they just appear as plain text on the page - no "status message" theming.

![About___Rules](https://user-images.githubusercontent.com/3144571/76603059-41ee3600-64da-11ea-8bfa-f47761913f53.png)

Was this your intention?

**Comment by Graham-72** [comment]
> Was this your intention?

No! My mistake/misunderstanding.

**Comment by olafgrabienski** [comment]
> "Show a message on the site" action should have the new "info" type

In the meantime, this seems to be possible, at least on one of my Backdrop sites which uses Rules 1.x-2.1.5. @laryn Do you also see the info message type in Rules?

**Comment by laryn** [comment]
@olafgrabienski Yes, info does show up as an option (the default option, actually). However the list does include a bunch of unstyled "status" selections. For example, if you select "Emergency" it comes out with no styling as @stpaultim noted:

![Screen Shot 2021-10-27 at 2 21 28 PM](https://user-images.githubusercontent.com/871421/139132843-f19519e4-693b-4995-9e9f-98beabd5bdc4.jpg)

**Comment by olafgrabienski** [comment]
> However the list does include a bunch of unstyled "status" selections.

I see! New issue then? (And close this one?)

**Comment by laryn** [comment]
@olafgrabienski Those extraneous status selections came in on this issue and I think could be simply removed on this issue as well.

**Comment by olafgrabienski** [comment]
> Those extraneous status selections came in on this issue and I think could be simply removed on this issue as well.

Agreed! (Sorry, I hadn't read all comments and wasn't aware of the PR which added all the other message types.)
