### ISSUE TITLE
Core Actions are not working

### ISSUE THREAD

**Issue by Acertijo** [backdrop-contrib/rules#77]
I can´t unpublish content with Rules, no matter what event is or condition, it has no effect

- New Installation
- Install Rules and dependences Entity Plus and UI
- Create any Rule event and the action "Unpublish content"

The log shows this error "action node_unpublish: Execution implementation is missing."

**Comment by laryn** [comment]
I can confirm the bug. I suspect it has to do with changes to the core actions / VBO in core but haven't had a chance to dig deeper.

**Comment by laryn** [comment]
See:

 - https://github.com/backdrop/backdrop-issues/issues/168
 - https://github.com/backdrop-contrib/rules/blob/80681af483c096284d76c06722b55bd8b035c45e/modules/node.rules.inc#L106-L125

**Comment by laryn** [comment]
It turns out this was more because of the node actions being moved into a separate file. I tested simply adding this file:

> require_once BACKDROP_ROOT . '/core/modules/node/node.actions.inc';

That worked but gave a warning because at some point the function had changed slightly and the second element was now passed by reference, which Rules was not doing. I decided it may be simpler to just include Rules-specific versions of these actions since the code duplication is not great and it prevents having to do any "handpicking" and custom handling outside of the regular Rules action system.

@Acertijo if you still need this, please test the latest development version and report back here.
https://github.com/backdrop-contrib/rules/archive/refs/heads/1.x-2.x.zip
