### ISSUE TITLE
Ubercart-Rules watchdog messages are all errors

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/rules#95]
I'll cross-post this until determined which module is doing this, but all watchdog messages from Ubercart Rules seem to be showing up as errors:

![image](https://user-images.githubusercontent.com/871421/140546476-9eda7e6f-33b2-4335-b62a-769b6f6564af.png)

--
*Cross-post: https://github.com/backdrop-contrib/ubercart/issues/288*

**Comment by laryn** [comment]
Noting for the future when I have time to test... An initial guess is that adding the "info" status is throwing this logic off:

 - https://github.com/backdrop-contrib/rules/blob/77206ad7d86271cef137ad21c659bbc2f4738c5a/rules.module#L244

Related:

 - https://github.com/backdrop-contrib/rules/issues/70

**Comment by bugfolder** [comment]
I am seeing this too, and I'm pretty sure that the problem lies in improperly importing Rules settings from D7 during upgrade.

For any site that is exhibiting this behavior, go examine file rules.settings.json in the active config directory. You'll probably see something like this:

```
{
    "_config_name": "rules.settings",
    "rules_log_errors": "RulesLog::WARN",
    "rules_log_level": "self::INFO",
    "rules_debug_log": "0",
    "rules_debug": "RulesLog::WARN",
    "language_content_type_page": "1",
    "rules_path_cleaning_callback": "rules_path_default_cleaning_method",
    "rules_path_replacement_char": "-",
    "rules_path_lower_case": "TRUE",
    "rules_clean_path": "array(\"/[^a-zA-Z0-9\\-_]+/\", $replace)",
    "rules_path_transliteration": "TRUE"
}
```

Those values `'RulesLog::WARN'` and `'self::INFO'` should be numeric constants, not strings. Indeed, if you change the settings at admin/config/workflow/rules/settings, then save them, then go re-examine the settings config file, you'll see that the altered values are now numeric.

So, how did this happen?

In `rules_update_1000()` in file rules.install, we see this:

```
function rules_update_1000() {
  // Migrate variables to config.
  $config = config('rules.settings');
  $config->set('rules_log_errors', update_variable_get('rules_log_errors', 'RulesLog::WARN'));
  $config->set('rules_log_level', update_variable_get('rules_log_level', 'self::INFO'));
  $config->set('rules_debug_log', update_variable_get('rules_debug_log', '0'));
  $config->set('rules_debug', update_variable_get('rules_log_debug', 'RulesLog::WARN'));
  $config->set('language_content_type_page', update_variable_get('language_content_type_page', '1'));
...
```

Presumably coder_upgrade naïvely converted the class constants to literal strings, rather than the proper numeric values. So the solution should be as follows:

* On already-upgraded sites, re-save the rules settings at admin/config/workflow/rules/settings.
* For future posterity, modify rules_update_1000() to un-quote those class constants. PR to follow.

**Comment by bugfolder** [comment]
Of course, `'self::INFO'` should become `RulesLog::INFO`, since `self` doesn't exist at this point.

**Comment by laryn** [comment]
Confirmed the diagnosis and the fix. Thanks @bugfolder!
